<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>shiguangji</artifactId>
        <groupId>com.shiguangji</groupId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>shiguangji-file</artifactId>

    <description>
        file文件存储模块（本地/S3兼容存储策略）
    </description>

    <dependencies>

        <!-- 通用工具-->
        <dependency>
            <groupId>com.shiguangji</groupId>
            <artifactId>shiguangji-common</artifactId>
        </dependency>

        <!-- 测试-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

</project>
